apiVersion: v1
kind: Namespace
metadata:
  name: rom-operator-bridge
---
apiVersion: v1
kind: Service
metadata:
  name: rom-operator-bridge
  namespace: rom-operator-bridge
spec:
  ports:
    - name: http
      port: 7410
      targetPort: 7410
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rom-operator-bridge
  namespace: rom-operator-bridge
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rombridge.birb.homes
      secretName: rom-operator-bridge-tls
  rules:
    - host: rombridge.birb.homes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rom-operator-bridge
                port:
                  number: 7410
